Repository ExtensionEngine/tailor-teaching-elements, pull requests merged in 2019-09, with the labels that each got.

#43 return default type if options have no type
  examples/data/dragDrop.json
  examples/data/fillBlank.json
  examples/data/matchingQuestion.json
  examples/data/multipleChoice.json
  examples/data/numericResponse.json
  examples/data/singleChoice.json
  examples/data/trueFalse.json
  src/teaching-element/Assessment/DragDrop.vue
  src/teaching-element/Assessment/MultipleChoice.vue
  src/teaching-element/Assessment/SingleChoice.vue
  src/teaching-element/Assessment/TrueFalse.vue
Labels: needs code review

#44 TE-jodit-html
  examples/data/joditHtml.json
  package-lock.json
  package.json
  src/teaching-element/JoditHtml.vue
  src/teaching-element/index.vue
  src/types.js
Labels: ready for merge

#46 TE-file
  examples/data/file.json
  src/teaching-element/File.vue
  src/teaching-element/index.vue
  src/types.js
Labels: ready for merge

#47 Add support for reflections
  examples/App.vue
  examples/components/Navbar.vue
  examples/components/SelectAssessment.vue
  examples/components/Showcase.vue
  examples/data/accordion.json
  examples/data/break.json
  examples/data/brightcoveVideo.json
  examples/data/carousel.json
  examples/data/dragDrop.json
  examples/data/embed.json
  examples/data/fillBlank.json
  examples/data/html.json
  examples/data/image.json
  examples/data/matchingQuestion.json
  examples/data/modal.json
  examples/data/multipleChoice.json
  examples/data/numericResponse.json
  examples/data/singleChoice.json
  examples/data/table.json
  examples/data/textResponse.json
  examples/data/video.json
  src/teaching-element/Assessment/index.vue
  src/teaching-element/Reflection.vue
  src/teaching-element/index.vue
  src/types.js
Labels: needs more work
